export enum RolesEnum{
    ROLE_ADMIN = 'ROLE_ADMIN',
    ROLE_TEST_MANAGER = 'ROLE_TEST_MANAGER',
    ROLE_PROJECT_MANAGER = 'ROLE_PROJECT_MANAGER',
    ROLE_DEVELOPER = 'ROLE_DEVELOPER',
    ROLE_TEST = "ROLE_TEST"
}